
GET https://crestem-ong-api.staging.heroesof.tech/api/reports?populate[0]=user.userSessions.mentor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzUsImlhdCI6MTc2MjQxNTE2NywiZXhwIjoxNzY1MDA3MTY3fQ.AavHrS6VssAtnfpobO9tk-j4vwERXoHEQwLmDnf24Sw
###