/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authEmailSentRouteImport } from './routes/(auth)/email-sent'
import { Route as authConfirmEmailRouteImport } from './routes/(auth)/confirm-email'
import { Route as appMatrixRouteImport } from './routes/(app)/matrix'
import { Route as appUsersRouteRouteImport } from './routes/(app)/users/route'
import { Route as appReportsRouteRouteImport } from './routes/(app)/reports/route'
import { Route as appProgramsRouteRouteImport } from './routes/(app)/programs/route'
import { Route as appProfileRouteRouteImport } from './routes/(app)/profile/route'
import { Route as appEvaluationRouteRouteImport } from './routes/(app)/evaluation/route'
import { Route as appCreateRouteRouteImport } from './routes/(app)/create/route'
import { Route as appUsersIndexRouteImport } from './routes/(app)/users/index'
import { Route as appReportsIndexRouteImport } from './routes/(app)/reports/index'
import { Route as appProgramsIndexRouteImport } from './routes/(app)/programs/index'
import { Route as appProfileIndexRouteImport } from './routes/(app)/profile/index'
import { Route as appMentorsIndexRouteImport } from './routes/(app)/mentors/index'
import { Route as appActivitiesIndexRouteImport } from './routes/(app)/activities/index'
import { Route as appUsersUserIdRouteImport } from './routes/(app)/users/$userId'
import { Route as appReportsReportIdRouteImport } from './routes/(app)/reports/$reportId'
import { Route as appProgramsProgramIdRouteImport } from './routes/(app)/programs/$programId'
import { Route as appProfileEditRouteImport } from './routes/(app)/profile/edit'
import { Route as appEvaluationEvaluationIdRouteImport } from './routes/(app)/evaluation/$evaluationId'
import { Route as appCreateUserRouteImport } from './routes/(app)/create/user'
import { Route as appCreateReportRouteImport } from './routes/(app)/create/report'
import { Route as appCreateProgramRouteImport } from './routes/(app)/create/program'
import { Route as appCreateMentorRouteImport } from './routes/(app)/create/mentor'
import { Route as appCreateActivityRouteImport } from './routes/(app)/create/activity'
import { Route as appActivitiesActivityIdRouteImport } from './routes/(app)/activities/$activityId'
import { Route as appMentorsMentorIdIndexRouteImport } from './routes/(app)/mentors/$mentorId/index'
import { Route as appMentorsMentorIdEditRouteImport } from './routes/(app)/mentors/$mentorId/edit'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authEmailSentRoute = authEmailSentRouteImport.update({
  id: '/email-sent',
  path: '/email-sent',
  getParentRoute: () => authRouteRoute,
} as any)
const authConfirmEmailRoute = authConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => authRouteRoute,
} as any)
const appMatrixRoute = appMatrixRouteImport.update({
  id: '/(app)/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const appUsersRouteRoute = appUsersRouteRouteImport.update({
  id: '/(app)/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const appReportsRouteRoute = appReportsRouteRouteImport.update({
  id: '/(app)/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const appProgramsRouteRoute = appProgramsRouteRouteImport.update({
  id: '/(app)/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRouteRoute = appProfileRouteRouteImport.update({
  id: '/(app)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const appEvaluationRouteRoute = appEvaluationRouteRouteImport.update({
  id: '/(app)/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const appCreateRouteRoute = appCreateRouteRouteImport.update({
  id: '/(app)/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const appUsersIndexRoute = appUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appUsersRouteRoute,
} as any)
const appReportsIndexRoute = appReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appReportsRouteRoute,
} as any)
const appProgramsIndexRoute = appProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appProgramsRouteRoute,
} as any)
const appProfileIndexRoute = appProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appProfileRouteRoute,
} as any)
const appMentorsIndexRoute = appMentorsIndexRouteImport.update({
  id: '/(app)/mentors/',
  path: '/mentors/',
  getParentRoute: () => rootRouteImport,
} as any)
const appActivitiesIndexRoute = appActivitiesIndexRouteImport.update({
  id: '/(app)/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const appUsersUserIdRoute = appUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => appUsersRouteRoute,
} as any)
const appReportsReportIdRoute = appReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => appReportsRouteRoute,
} as any)
const appProgramsProgramIdRoute = appProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => appProgramsRouteRoute,
} as any)
const appProfileEditRoute = appProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => appProfileRouteRoute,
} as any)
const appEvaluationEvaluationIdRoute =
  appEvaluationEvaluationIdRouteImport.update({
    id: '/$evaluationId',
    path: '/$evaluationId',
    getParentRoute: () => appEvaluationRouteRoute,
  } as any)
const appCreateUserRoute = appCreateUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => appCreateRouteRoute,
} as any)
const appCreateReportRoute = appCreateReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => appCreateRouteRoute,
} as any)
const appCreateProgramRoute = appCreateProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => appCreateRouteRoute,
} as any)
const appCreateMentorRoute = appCreateMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => appCreateRouteRoute,
} as any)
const appCreateActivityRoute = appCreateActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => appCreateRouteRoute,
} as any)
const appActivitiesActivityIdRoute = appActivitiesActivityIdRouteImport.update({
  id: '/(app)/activities/$activityId',
  path: '/activities/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const appMentorsMentorIdIndexRoute = appMentorsMentorIdIndexRouteImport.update({
  id: '/(app)/mentors/$mentorId/',
  path: '/mentors/$mentorId/',
  getParentRoute: () => rootRouteImport,
} as any)
const appMentorsMentorIdEditRoute = appMentorsMentorIdEditRouteImport.update({
  id: '/(app)/mentors/$mentorId/edit',
  path: '/mentors/$mentorId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/create': typeof appCreateRouteRouteWithChildren
  '/evaluation': typeof appEvaluationRouteRouteWithChildren
  '/profile': typeof appProfileRouteRouteWithChildren
  '/programs': typeof appProgramsRouteRouteWithChildren
  '/reports': typeof appReportsRouteRouteWithChildren
  '/users': typeof appUsersRouteRouteWithChildren
  '/matrix': typeof appMatrixRoute
  '/confirm-email': typeof authConfirmEmailRoute
  '/email-sent': typeof authEmailSentRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/activities/$activityId': typeof appActivitiesActivityIdRoute
  '/create/activity': typeof appCreateActivityRoute
  '/create/mentor': typeof appCreateMentorRoute
  '/create/program': typeof appCreateProgramRoute
  '/create/report': typeof appCreateReportRoute
  '/create/user': typeof appCreateUserRoute
  '/evaluation/$evaluationId': typeof appEvaluationEvaluationIdRoute
  '/profile/edit': typeof appProfileEditRoute
  '/programs/$programId': typeof appProgramsProgramIdRoute
  '/reports/$reportId': typeof appReportsReportIdRoute
  '/users/$userId': typeof appUsersUserIdRoute
  '/activities': typeof appActivitiesIndexRoute
  '/mentors': typeof appMentorsIndexRoute
  '/profile/': typeof appProfileIndexRoute
  '/programs/': typeof appProgramsIndexRoute
  '/reports/': typeof appReportsIndexRoute
  '/users/': typeof appUsersIndexRoute
  '/mentors/$mentorId/edit': typeof appMentorsMentorIdEditRoute
  '/mentors/$mentorId': typeof appMentorsMentorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/create': typeof appCreateRouteRouteWithChildren
  '/evaluation': typeof appEvaluationRouteRouteWithChildren
  '/matrix': typeof appMatrixRoute
  '/confirm-email': typeof authConfirmEmailRoute
  '/email-sent': typeof authEmailSentRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/activities/$activityId': typeof appActivitiesActivityIdRoute
  '/create/activity': typeof appCreateActivityRoute
  '/create/mentor': typeof appCreateMentorRoute
  '/create/program': typeof appCreateProgramRoute
  '/create/report': typeof appCreateReportRoute
  '/create/user': typeof appCreateUserRoute
  '/evaluation/$evaluationId': typeof appEvaluationEvaluationIdRoute
  '/profile/edit': typeof appProfileEditRoute
  '/programs/$programId': typeof appProgramsProgramIdRoute
  '/reports/$reportId': typeof appReportsReportIdRoute
  '/users/$userId': typeof appUsersUserIdRoute
  '/activities': typeof appActivitiesIndexRoute
  '/mentors': typeof appMentorsIndexRoute
  '/profile': typeof appProfileIndexRoute
  '/programs': typeof appProgramsIndexRoute
  '/reports': typeof appReportsIndexRoute
  '/users': typeof appUsersIndexRoute
  '/mentors/$mentorId/edit': typeof appMentorsMentorIdEditRoute
  '/mentors/$mentorId': typeof appMentorsMentorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/create': typeof appCreateRouteRouteWithChildren
  '/(app)/evaluation': typeof appEvaluationRouteRouteWithChildren
  '/(app)/profile': typeof appProfileRouteRouteWithChildren
  '/(app)/programs': typeof appProgramsRouteRouteWithChildren
  '/(app)/reports': typeof appReportsRouteRouteWithChildren
  '/(app)/users': typeof appUsersRouteRouteWithChildren
  '/(app)/matrix': typeof appMatrixRoute
  '/(auth)/confirm-email': typeof authConfirmEmailRoute
  '/(auth)/email-sent': typeof authEmailSentRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(app)/activities/$activityId': typeof appActivitiesActivityIdRoute
  '/(app)/create/activity': typeof appCreateActivityRoute
  '/(app)/create/mentor': typeof appCreateMentorRoute
  '/(app)/create/program': typeof appCreateProgramRoute
  '/(app)/create/report': typeof appCreateReportRoute
  '/(app)/create/user': typeof appCreateUserRoute
  '/(app)/evaluation/$evaluationId': typeof appEvaluationEvaluationIdRoute
  '/(app)/profile/edit': typeof appProfileEditRoute
  '/(app)/programs/$programId': typeof appProgramsProgramIdRoute
  '/(app)/reports/$reportId': typeof appReportsReportIdRoute
  '/(app)/users/$userId': typeof appUsersUserIdRoute
  '/(app)/activities/': typeof appActivitiesIndexRoute
  '/(app)/mentors/': typeof appMentorsIndexRoute
  '/(app)/profile/': typeof appProfileIndexRoute
  '/(app)/programs/': typeof appProgramsIndexRoute
  '/(app)/reports/': typeof appReportsIndexRoute
  '/(app)/users/': typeof appUsersIndexRoute
  '/(app)/mentors/$mentorId/edit': typeof appMentorsMentorIdEditRoute
  '/(app)/mentors/$mentorId/': typeof appMentorsMentorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/evaluation'
    | '/profile'
    | '/programs'
    | '/reports'
    | '/users'
    | '/matrix'
    | '/confirm-email'
    | '/email-sent'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/activities/$activityId'
    | '/create/activity'
    | '/create/mentor'
    | '/create/program'
    | '/create/report'
    | '/create/user'
    | '/evaluation/$evaluationId'
    | '/profile/edit'
    | '/programs/$programId'
    | '/reports/$reportId'
    | '/users/$userId'
    | '/activities'
    | '/mentors'
    | '/profile/'
    | '/programs/'
    | '/reports/'
    | '/users/'
    | '/mentors/$mentorId/edit'
    | '/mentors/$mentorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/evaluation'
    | '/matrix'
    | '/confirm-email'
    | '/email-sent'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/activities/$activityId'
    | '/create/activity'
    | '/create/mentor'
    | '/create/program'
    | '/create/report'
    | '/create/user'
    | '/evaluation/$evaluationId'
    | '/profile/edit'
    | '/programs/$programId'
    | '/reports/$reportId'
    | '/users/$userId'
    | '/activities'
    | '/mentors'
    | '/profile'
    | '/programs'
    | '/reports'
    | '/users'
    | '/mentors/$mentorId/edit'
    | '/mentors/$mentorId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(app)/create'
    | '/(app)/evaluation'
    | '/(app)/profile'
    | '/(app)/programs'
    | '/(app)/reports'
    | '/(app)/users'
    | '/(app)/matrix'
    | '/(auth)/confirm-email'
    | '/(auth)/email-sent'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(app)/activities/$activityId'
    | '/(app)/create/activity'
    | '/(app)/create/mentor'
    | '/(app)/create/program'
    | '/(app)/create/report'
    | '/(app)/create/user'
    | '/(app)/evaluation/$evaluationId'
    | '/(app)/profile/edit'
    | '/(app)/programs/$programId'
    | '/(app)/reports/$reportId'
    | '/(app)/users/$userId'
    | '/(app)/activities/'
    | '/(app)/mentors/'
    | '/(app)/profile/'
    | '/(app)/programs/'
    | '/(app)/reports/'
    | '/(app)/users/'
    | '/(app)/mentors/$mentorId/edit'
    | '/(app)/mentors/$mentorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  appCreateRouteRoute: typeof appCreateRouteRouteWithChildren
  appEvaluationRouteRoute: typeof appEvaluationRouteRouteWithChildren
  appProfileRouteRoute: typeof appProfileRouteRouteWithChildren
  appProgramsRouteRoute: typeof appProgramsRouteRouteWithChildren
  appReportsRouteRoute: typeof appReportsRouteRouteWithChildren
  appUsersRouteRoute: typeof appUsersRouteRouteWithChildren
  appMatrixRoute: typeof appMatrixRoute
  appActivitiesActivityIdRoute: typeof appActivitiesActivityIdRoute
  appActivitiesIndexRoute: typeof appActivitiesIndexRoute
  appMentorsIndexRoute: typeof appMentorsIndexRoute
  appMentorsMentorIdEditRoute: typeof appMentorsMentorIdEditRoute
  appMentorsMentorIdIndexRoute: typeof appMentorsMentorIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/email-sent': {
      id: '/(auth)/email-sent'
      path: '/email-sent'
      fullPath: '/email-sent'
      preLoaderRoute: typeof authEmailSentRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/confirm-email': {
      id: '/(auth)/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof authConfirmEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/matrix': {
      id: '/(app)/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof appMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/users': {
      id: '/(app)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof appUsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/reports': {
      id: '/(app)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof appReportsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/programs': {
      id: '/(app)/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof appProgramsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/evaluation': {
      id: '/(app)/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof appEvaluationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/create': {
      id: '/(app)/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof appCreateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/users/': {
      id: '/(app)/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof appUsersIndexRouteImport
      parentRoute: typeof appUsersRouteRoute
    }
    '/(app)/reports/': {
      id: '/(app)/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof appReportsIndexRouteImport
      parentRoute: typeof appReportsRouteRoute
    }
    '/(app)/programs/': {
      id: '/(app)/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof appProgramsIndexRouteImport
      parentRoute: typeof appProgramsRouteRoute
    }
    '/(app)/profile/': {
      id: '/(app)/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof appProfileIndexRouteImport
      parentRoute: typeof appProfileRouteRoute
    }
    '/(app)/mentors/': {
      id: '/(app)/mentors/'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof appMentorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/activities/': {
      id: '/(app)/activities/'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof appActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/users/$userId': {
      id: '/(app)/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof appUsersUserIdRouteImport
      parentRoute: typeof appUsersRouteRoute
    }
    '/(app)/reports/$reportId': {
      id: '/(app)/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof appReportsReportIdRouteImport
      parentRoute: typeof appReportsRouteRoute
    }
    '/(app)/programs/$programId': {
      id: '/(app)/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof appProgramsProgramIdRouteImport
      parentRoute: typeof appProgramsRouteRoute
    }
    '/(app)/profile/edit': {
      id: '/(app)/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof appProfileEditRouteImport
      parentRoute: typeof appProfileRouteRoute
    }
    '/(app)/evaluation/$evaluationId': {
      id: '/(app)/evaluation/$evaluationId'
      path: '/$evaluationId'
      fullPath: '/evaluation/$evaluationId'
      preLoaderRoute: typeof appEvaluationEvaluationIdRouteImport
      parentRoute: typeof appEvaluationRouteRoute
    }
    '/(app)/create/user': {
      id: '/(app)/create/user'
      path: '/user'
      fullPath: '/create/user'
      preLoaderRoute: typeof appCreateUserRouteImport
      parentRoute: typeof appCreateRouteRoute
    }
    '/(app)/create/report': {
      id: '/(app)/create/report'
      path: '/report'
      fullPath: '/create/report'
      preLoaderRoute: typeof appCreateReportRouteImport
      parentRoute: typeof appCreateRouteRoute
    }
    '/(app)/create/program': {
      id: '/(app)/create/program'
      path: '/program'
      fullPath: '/create/program'
      preLoaderRoute: typeof appCreateProgramRouteImport
      parentRoute: typeof appCreateRouteRoute
    }
    '/(app)/create/mentor': {
      id: '/(app)/create/mentor'
      path: '/mentor'
      fullPath: '/create/mentor'
      preLoaderRoute: typeof appCreateMentorRouteImport
      parentRoute: typeof appCreateRouteRoute
    }
    '/(app)/create/activity': {
      id: '/(app)/create/activity'
      path: '/activity'
      fullPath: '/create/activity'
      preLoaderRoute: typeof appCreateActivityRouteImport
      parentRoute: typeof appCreateRouteRoute
    }
    '/(app)/activities/$activityId': {
      id: '/(app)/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof appActivitiesActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/mentors/$mentorId/': {
      id: '/(app)/mentors/$mentorId/'
      path: '/mentors/$mentorId'
      fullPath: '/mentors/$mentorId'
      preLoaderRoute: typeof appMentorsMentorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/mentors/$mentorId/edit': {
      id: '/(app)/mentors/$mentorId/edit'
      path: '/mentors/$mentorId/edit'
      fullPath: '/mentors/$mentorId/edit'
      preLoaderRoute: typeof appMentorsMentorIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authConfirmEmailRoute: typeof authConfirmEmailRoute
  authEmailSentRoute: typeof authEmailSentRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authConfirmEmailRoute: authConfirmEmailRoute,
  authEmailSentRoute: authEmailSentRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface appCreateRouteRouteChildren {
  appCreateActivityRoute: typeof appCreateActivityRoute
  appCreateMentorRoute: typeof appCreateMentorRoute
  appCreateProgramRoute: typeof appCreateProgramRoute
  appCreateReportRoute: typeof appCreateReportRoute
  appCreateUserRoute: typeof appCreateUserRoute
}

const appCreateRouteRouteChildren: appCreateRouteRouteChildren = {
  appCreateActivityRoute: appCreateActivityRoute,
  appCreateMentorRoute: appCreateMentorRoute,
  appCreateProgramRoute: appCreateProgramRoute,
  appCreateReportRoute: appCreateReportRoute,
  appCreateUserRoute: appCreateUserRoute,
}

const appCreateRouteRouteWithChildren = appCreateRouteRoute._addFileChildren(
  appCreateRouteRouteChildren,
)

interface appEvaluationRouteRouteChildren {
  appEvaluationEvaluationIdRoute: typeof appEvaluationEvaluationIdRoute
}

const appEvaluationRouteRouteChildren: appEvaluationRouteRouteChildren = {
  appEvaluationEvaluationIdRoute: appEvaluationEvaluationIdRoute,
}

const appEvaluationRouteRouteWithChildren =
  appEvaluationRouteRoute._addFileChildren(appEvaluationRouteRouteChildren)

interface appProfileRouteRouteChildren {
  appProfileEditRoute: typeof appProfileEditRoute
  appProfileIndexRoute: typeof appProfileIndexRoute
}

const appProfileRouteRouteChildren: appProfileRouteRouteChildren = {
  appProfileEditRoute: appProfileEditRoute,
  appProfileIndexRoute: appProfileIndexRoute,
}

const appProfileRouteRouteWithChildren = appProfileRouteRoute._addFileChildren(
  appProfileRouteRouteChildren,
)

interface appProgramsRouteRouteChildren {
  appProgramsProgramIdRoute: typeof appProgramsProgramIdRoute
  appProgramsIndexRoute: typeof appProgramsIndexRoute
}

const appProgramsRouteRouteChildren: appProgramsRouteRouteChildren = {
  appProgramsProgramIdRoute: appProgramsProgramIdRoute,
  appProgramsIndexRoute: appProgramsIndexRoute,
}

const appProgramsRouteRouteWithChildren =
  appProgramsRouteRoute._addFileChildren(appProgramsRouteRouteChildren)

interface appReportsRouteRouteChildren {
  appReportsReportIdRoute: typeof appReportsReportIdRoute
  appReportsIndexRoute: typeof appReportsIndexRoute
}

const appReportsRouteRouteChildren: appReportsRouteRouteChildren = {
  appReportsReportIdRoute: appReportsReportIdRoute,
  appReportsIndexRoute: appReportsIndexRoute,
}

const appReportsRouteRouteWithChildren = appReportsRouteRoute._addFileChildren(
  appReportsRouteRouteChildren,
)

interface appUsersRouteRouteChildren {
  appUsersUserIdRoute: typeof appUsersUserIdRoute
  appUsersIndexRoute: typeof appUsersIndexRoute
}

const appUsersRouteRouteChildren: appUsersRouteRouteChildren = {
  appUsersUserIdRoute: appUsersUserIdRoute,
  appUsersIndexRoute: appUsersIndexRoute,
}

const appUsersRouteRouteWithChildren = appUsersRouteRoute._addFileChildren(
  appUsersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  appCreateRouteRoute: appCreateRouteRouteWithChildren,
  appEvaluationRouteRoute: appEvaluationRouteRouteWithChildren,
  appProfileRouteRoute: appProfileRouteRouteWithChildren,
  appProgramsRouteRoute: appProgramsRouteRouteWithChildren,
  appReportsRouteRoute: appReportsRouteRouteWithChildren,
  appUsersRouteRoute: appUsersRouteRouteWithChildren,
  appMatrixRoute: appMatrixRoute,
  appActivitiesActivityIdRoute: appActivitiesActivityIdRoute,
  appActivitiesIndexRoute: appActivitiesIndexRoute,
  appMentorsIndexRoute: appMentorsIndexRoute,
  appMentorsMentorIdEditRoute: appMentorsMentorIdEditRoute,
  appMentorsMentorIdIndexRoute: appMentorsMentorIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
